services:

  # mdcatalog:
  #   container_name: mdcatalog
  #   image: mdcatalog
  #   build: .
  #   env_file:
  #     - .env
  #   volumes:
  #     - $PWD:/mdcatalog
  #   stdin_open: true
  #   tty: true
  #   depends_on:
  #     - postgres
  #   restart: unless-stopped
  #   ports:
  #     - 8000:8000

  postgres:
    # container_name: mdcatalogdb
    image: postgres:latest
    env_file: .env.dev
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  admin:
    image: adminer
    depends_on:
      - postgres
    ports:
      - 8080:8080

volumes:
  pgdata:
