"""Changed Asset description to TEXT

Revision ID: 02d2a1fde23e
Revises: 32d9846e7399
Create Date: 2024-08-08 21:21:31.883483

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "02d2a1fde23e"
down_revision: Union[str, None] = "32d9846e7399"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "assets",
        "description",
        existing_type=sa.VARCHAR(length=1500),
        type_=sa.Text(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "assets",
        "description",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(length=1500),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
