"""Changed domain-assets relations

Revision ID: 30e66c85eb30
Revises: d34a4c3a6ed1
Create Date: 2024-08-08 21:04:33.821041

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "30e66c85eb30"
down_revision: Union[str, None] = "d34a4c3a6ed1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
