"""Increased description field size for Asset

Revision ID: 32d9846e7399
Revises: 46007afda3ea
Create Date: 2024-08-08 21:18:27.090742

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "32d9846e7399"
down_revision: Union[str, None] = "46007afda3ea"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "assets",
        "description",
        existing_type=sa.VARCHAR(length=500),
        type_=sa.String(length=1500),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "assets",
        "description",
        existing_type=sa.String(length=1500),
        type_=sa.VARCHAR(length=500),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
