"""Added description field to Domain model

Revision ID: 6b649854b901
Revises: 491de2226b54
Create Date: 2024-08-08 20:22:07.359654

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6b649854b901"
down_revision: Union[str, None] = "491de2226b54"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "domains", sa.Column("description", sa.String(length=250), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("domains", "description")
    # ### end Alembic commands ###
