"""Added description field to Asset model

Revision ID: 8b62193812e5
Revises: 6b649854b901
Create Date: 2024-08-08 20:28:07.082738

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8b62193812e5"
down_revision: Union[str, None] = "6b649854b901"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "assets", sa.Column("description", sa.String(length=500), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("assets", "description")
    # ### end Alembic commands ###
