"""Modified asset keywords model

Revision ID: 92e01ef6ad0f
Revises: ac13fdd5117c
Create Date: 2024-08-20 13:56:04.715331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92e01ef6ad0f'
down_revision: Union[str, None] = 'ac13fdd5117c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('keywords_asset_id_fkey', 'keywords', type_='foreignkey')
    op.create_foreign_key(None, 'keywords', 'assets', ['asset_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'keywords', type_='foreignkey')
    op.create_foreign_key('keywords_asset_id_fkey', 'keywords', 'domains', ['asset_id'], ['id'])
    # ### end Alembic commands ###
