"""Added fk for domain-assets relations

Revision ID: a291fcee6118
Revises: 30e66c85eb30
Create Date: 2024-08-08 21:06:42.266936

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a291fcee6118"
down_revision: Union[str, None] = "30e66c85eb30"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("assets", sa.Column("domain_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "assets", "domains", ["domain_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "assets", type_="foreignkey")
    op.drop_column("assets", "domain_id")
    # ### end Alembic commands ###
