"""Added metadata_url to Asset

Revision ID: d131b2059af8
Revises: 02d2a1fde23e
Create Date: 2024-08-08 22:02:28.751877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd131b2059af8'
down_revision: Union[str, None] = '02d2a1fde23e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('metadata_url', sa.String(length=1000), nullable=True))
    op.create_unique_constraint(None, 'assets', ['metadata_url'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'assets', type_='unique')
    op.drop_column('assets', 'metadata_url')
    # ### end Alembic commands ###
