"""Changed root_domain_name in Domain model to unique is false

Revision ID: d34a4c3a6ed1
Revises: 8b62193812e5
Create Date: 2024-08-08 20:50:08.985769

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d34a4c3a6ed1"
down_revision: Union[str, None] = "8b62193812e5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("domains_root_domain_name_key", "domains", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "domains_root_domain_name_key", "domains", ["root_domain_name"]
    )
    # ### end Alembic commands ###
